CREATE TABLE connection_config_defaults (
    institution_id uuid NOT NULL PRIMARY KEY,
    routing_number VARCHAR(9) NOT NULL,
    active boolean DEFAULT true,
    test_env boolean DEFAULT true,
    base_url VARCHAR(256) NOT NULL,
    jxchange_env_type VARCHAR(16) NOT NULL default 'PROD',
    jxchange_audit_user_id VARCHAR(64) NOT NULL,
    jxchange_audit_workstation_id VARCHAR(64) NOT NULL,
    consumer_name_override VARCHAR(128),
    consumer_product_override VARCHAR(128),
    valid_consumer_name_override VARCHAR(128),
    valid_consumer_product_override VARCHAR(128),
    log_interaction_always boolean DEFAULT false,
    use_ssn_for_account_search boolean DEFAULT false,
    use_customer_id_for_card_search boolean DEFAULT false,
    use_netteller_for_entitlements boolean DEFAULT false,
    has_netteller_cash_management boolean DEFAULT false,
    ims_org_id varchar(128),
    rsa_version varchar(16),
    transfer_fee numeric,
    mfa_gateway_url varchar(512),
    officer_code varchar(36)
);
